#ifndef LOGICAL_OPERATION_TYPES_H
#define LOGICAL_OPERATION_TYPES_H

namespace Domain {

enum LOGICAL_OPERATION_TYPE
{
    LOGICAL_NONE = 0,
    LOGICAL_OR   = 1,
    LOGICAL_AND  = 2
};

}

#endif // LOGICAL_OPERATION_TYPES_H
