#ifndef HORUS_NETWORK_GLOBAL_H
#define HORUS_NETWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HORUS_NETWORK_LIBRARY)
#  define HORUS_NETWORK_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define HORUS_NETWORK_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HORUS_NETWORK_GLOBAL_H
